# Generated by Django 5.0 on 2024-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
                ),
                ("featured", models.BooleanField(db_index=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
        migrations.RemoveField(
            model_name="menu",
            name="inventory",
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
